name: EVM CI

on:
  push:
    paths:
      - "evm/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        working-directory: ./evm
        run: forge install

      - name: Check contract sizes
        working-directory: ./evm
        run: forge build --sizes

      - name: Check gas snapshots
        working-directory: ./evm
        run: forge snapshot --check

      - name: Run tests
        working-directory: ./evm
        run: forge test
        env:
          # Only fuzz intensely if we're running this action on a push to main or for a PR going into main:
          FOUNDRY_PROFILE: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'intense' }}
